DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json
accept: application/json

{
 "id": "8",
 "name": "daniel",
 "number": "0000-0000"
}

###

GET http://localhost:3001/api/persons
accept: application/json
###
